language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"

before_install:
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

before_script:
  # Configure `git` user
  - git config --global user.email "foundry-test@mailinator.com"
  - git config --global user.name "Foundry Test"

notifications:
  email: false
